### ISSUE TITLE
Error with edge type 'smooth-step'

### ISSUE THREAD

**Issue by VinskyStrauss** [artem-mangilev/ngx-vflow#104]
Hi, i just tried the new edge type 'smooth-step', but i always got an error for that type. I can still use the 'straigt' or 'bezier'.
This is my code for the createEdge or connect.
```
  public connect({ source, sourceHandle, targetHandle, target }: Connection) {
    this.edges = [
      ...this.edges,
      {
        id: `${source} ${sourceHandle} -> ${target} ${targetHandle}`,
        source,
        sourceHandle,
        target,
        targetHandle,
        curve: "bezier",
        type: "template",
        markers: {
          end: {
            type: "arrow-closed",
            width: 30,
            height: 30,
            color: "#000000",
          },
        },
      },
    ];
  }
```
I also use a custom angular SVG component for the edge and it looks something like this
```
import {
  ChangeDetectionStrategy,
  Component,
  inject,
  input,
  OnInit,
  output,
} from "@angular/core";

@Component({
  selector: "svg:g[eta-edge]",
  template: `
    @let ctx = edgeContext(); @if (ctx) {
    <ng-container>
      <svg:path
        selectable
        class="animate-path"
        [attr.d]="ctx.path()"
        [attr.stroke]="ctx.selected() ? '#0f4c75' : '#bbe1fa'"
        [attr.marker-end]="ctx.markerEnd()"
        fill="none"
        stroke-width="5"
        tabindex="0"
        (keydown.backspace)="ctx.selected()"
      />
    </ng-container>
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  styles: `
      .animate-path {
        stroke-dasharray: 100; /* High value to ensure the dash covers the entire path */
        stroke-dashoffset: 200; /* Initially, the path is not visible */
        animation: draw-path 2s linear infinite; /* 2-second animation to draw the path */
      }
  
      @keyframes draw-path {
        to {
          stroke-dashoffset: 0; /* Animate to 0 to make the path visible from start to end */
        }
      }
    `,
})
export class ScopeEdgeFlowComponent implements OnInit {
  edgeContext = input<any>();
  ngOnInit(): void {
    console.log("Edge initialized", this.edgeContext());
  }
}
```
But everytime i try to create the edge by connection 2 different nodes. I always got an error for the 'smooth-step' type. and this is the error in the console.log. Did i do something wrong for the edge, because i just followed the provided example in the documentation.
![image](https://github.com/user-attachments/assets/91c12612-7371-4748-b6da-c6963329029d)

**Comment by artem-mangilev** [comment]
I'll also check this during the week

**Comment by artem-mangilev** [comment]
I tried to reproduce the issue [here](https://stackblitz.com/edit/stackblitz-starters-5jskxgmz?file=src%2Fscope-edge.component.ts), but the code you provided seems to work fine. Could you please share the parent component that contains the `<vflow />` component?.

I also tested it in zoneless mode, and it works fine as well.

**Comment by VinskyStrauss** [comment]
Hi, sorry for the late reply.I'm looking forward for your reply. This is how i use it in the vflow
```
      <ng-template edge let-ctx>
        <svg:g eta-edge [edgeContext]="ctx" />
      </ng-template>
 ```
 
 and then this is the ScopeEdgeFlowComponent
 ```
 import {
  ChangeDetectionStrategy,
  Component,
  inject,
  input,
  OnInit,
  output,
} from "@angular/core";

@Component({
  selector: "svg:g[eta-edge]",
  template: `
    @let ctx = edgeContext(); @if (ctx) { @let color = ctx.edge.data.color;
    <ng-container>
      <svg:path
        selectable
        class="animate-path main-path"
        [attr.d]="ctx.path()"
        [attr.stroke]="color"
        [attr.marker-end]="ctx.markerEnd()"
        fill="none"
        stroke-width="5"
        tabindex="0"
        (keydown.backspace)="ctx.selected()"
      />
      <svg:path
        selectable
        class="animate-path moving-stroke"
        [attr.d]="ctx.path()"
        stroke="white"
        fill="none"
        stroke-width="3"
        [attr.stroke-dasharray]="ctx.strokeDasharray || '100'"
        [attr.stroke-dashoffset]="ctx.strokeDashoffset || '200'"
        tabindex="-1"
      />
    </ng-container>

    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  styles: `
    /* Style for the main path based on color */
    .main-path {
      stroke-linecap: round;
      stroke-linejoin: round;
    }

    /* Animated moving white stroke */
    .moving-stroke {
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-dasharray: 100; /* Matches the length of the path */
      stroke-dashoffset: 200; /* Initially offset */
      animation: move-white-stroke 2s linear infinite;
    }

    @keyframes move-white-stroke {
      to {
        stroke-dashoffset: 0; /* Move the stroke along the path */
      }
    }
    `,
})
export class ScopeEdgeFlowComponent implements OnInit {
  edgeContext = input<any>();
  ngOnInit(): void {
    console.log("Edge initialized", this.edgeContext());
    console.log("Color", this.edgeContext().edge.data.color);
  }
}
```

**Comment by artem-mangilev** [comment]
HI, I attempted to apply this code [here](https://stackblitz.com/edit/stackblitz-starters-fehamz6j?file=src%2Fscope-edge.component.ts,src%2Fmain.ts,src%2Fscope-edge.styles.scss) but couldn't reproduce the bug.

It would be extremely helpful if you could either create a StackBlitz project based on your code that reproduces the issue or give me access to the repository, if possible. Currently, I'm unable to understand why the error is occurring.

**Comment by VinskyStrauss** [comment]
Hi, i'm sorry for the late reply. Here is the [stackblitz](https://stackblitz.com/~/github.com/VinskyStrauss/simple-ngx-vflow) project,that you can try.

**Comment by artem-mangilev** [comment]
Hi! I tried changing the `curve` of `Edge`s to `'smooth-step'` and connecting the dots (green, red, and blue), but I didn’t encounter any errors. Could you please explain what I need to do to reproduce the error?
![image](https://github.com/user-attachments/assets/a3a3b727-75c2-4d91-bc23-5367392a626d)

**Comment by VinskyStrauss** [comment]
Hi, The picture, that you attached is the error. where the path is undefined and it won't show the newly created Edge right? Or did i do something wrong?

**Comment by VinskyStrauss** [comment]
Hi, sorry i just tested it again. Now it works. sorry to bother you. Thanks a lot for the fast reply

**Comment by artem-mangilev** [comment]
That's great! 
Don't worry, and thank you for using the library!
