### ISSUE TITLE
Selected functionality not working in CustomDynamicNodeComponent

### ISSUE THREAD

**Issue by StefanPopa99** [artem-mangilev/ngx-vflow#108]
Hi,

Here is a [stackblitz example](https://stackblitz.com/edit/stackblitz-starters-gawfsj86?file=src%2Fmy-custom-node%2Fmy-custom-node.component.ts)

I have a custom dynamic node component in which i set the selected status myself.
Problems:
1. If I click on other nodes, the current selection is not cleared
2. If i click on vflow area, the selection is not cleared

**Comment by artem-mangilev** [comment]
Hi! Should be fixed in this release: https://github.com/artem-mangilev/ngx-vflow/releases/tag/v1.0.0

**Comment by StefanPopa99** [comment]
I tried with 1.0 release and it works now. Thanks!
