### ISSUE TITLE
[newfeature]: inject node between nodes

### ISSUE THREAD

**Issue by leblancmeneses** [artem-mangilev/ngx-vflow#112]
palantir has a concept of being able to inject a node between two existing nodes.

![image](https://github.com/user-attachments/assets/a72d32e2-8927-4fab-a587-14da5991b538)

Given the curve chosen what would be a good solution to adding a button in the center of the connection?
https://www.ngx-vflow.org/features/curves

Thanks

**Comment by artem-mangilev** [comment]
Hi! This is probably what you are looking for

https://www.ngx-vflow.org/features/labels
