### ISSUE TITLE
[Request] Can you please add a workflow builder example

### ISSUE THREAD

**Issue by shyamal890** [artem-mangilev/ngx-vflow#44]
Something like https://reactflow.dev/examples/layout/workflow-builder

**Comment by artem-mangilev** [comment]
Thanks for your issue! I would like to implement something like this in future releases, it will require some important improvements:

- auto layout algorithms integration (Dagre.js)
- ability to draw edge to block itself, not it only attaches to handle
- API to fit all flow to viewport, adjust zoom

**Comment by artem-mangilev** [comment]
Hi there! I am planning to release this feature in v0.9.0 in August.

**Comment by artem-mangilev** [comment]
I released v0.9.0 with a workflow builder example based on  the Vizdom library, so I will close this issue

The page with example: https://www.ngx-vflow.org/workshops/layout/vizdom-layout
