### ISSUE TITLE
[Feature Request] - Node Toolbar

### ISSUE THREAD

**Issue by shyamal890** [artem-mangilev/ngx-vflow#46]
Something like 
![image](https://github.com/artem-mangilev/ngx-vflow/assets/6606965/ddf64591-bbb3-420c-bcef-92ae868d1b24)

**Comment by artem-mangilev** [comment]
Thanks for your issue!
You can kind of create custom logic for it with current lib state, like create a custom html node that shows toolbar inside of it on activate. But as I see a toolbar is outside of node, so this will require some additional work on lib side

**Comment by ChristofFritz** [comment]
I built something like this. The tricky part is to make it work in Safari. Position: relative & position: absolute doesn't really work with foreign object in safari. That's why I built it by rendering it outside the ngx-vflow component.

**Comment by artem-mangilev** [comment]
Hi there. I will add a toolbar in v0.15.0

**Comment by artem-mangilev** [comment]
Added [here](https://www.ngx-vflow.org/features/node-toolbar)
