### ISSUE TITLE
[Feature Request] - Export as image

### ISSUE THREAD

**Issue by FeironoX5** [artem-mangilev/ngx-vflow#75]

**Comment by FeironoX5** [comment]
This issue was opened because I couldn't figure out how to capture `vflowComponent`, with custom nodes. I was trying to use `html2canvas`, but some content wasn't rendered.

The description of my problem and solutions can be found here https://stackoverflow.com/questions/78815540/html2canvas-doesnt-capture-text-in-textarea-in-svg

**Comment by artem-mangilev** [comment]
I guess the easiest thing would be to implement export as PNG, so basically take a screenshot

**Comment by FeironoX5** [comment]
> I guess the easiest thing would be to implement export as PNG, so basically take a screenshot 

you mean, in package as function? html2canvas worked pretty well

**Comment by artem-mangilev** [comment]
I would like to not put this in core, maybe as some kind of plugin, but it requires to create plugin system first

**Comment by FeironoX5** [comment]
> I would like to not put this in core, maybe as some kind of plugin, but it requires to create plugin system first

Yes, that would be great, but you can only export to image by rerendering the whole component, which is a pretty hard task, that's why html2canvas exists. So, probably providing some recommendations in docs will be enough.
