### ISSUE TITLE
Nodes inside node/subflows?

### ISSUE THREAD

**Issue by lmrisdal** [artem-mangilev/ngx-vflow#78]
I am building a type of workflow builder thing for work, and one of the requirements we have is that we need to be able to group actions (nodes) inside another action. Very similar to how Azure Logic Apps work:
![Screenshot 2024-08-14 at 10 55 33](https://github.com/user-attachments/assets/894b4e77-79db-45fd-ae68-8ff134ef4dae)

Do you have any suggestions how I could achieve this? I did notice there is something called subflows on the roadmap, but nothing about what the plans are for that.

**Comment by elnipa** [comment]
A feature like this would be amazing. We have the same need.

**Comment by artem-mangilev** [comment]
Yeah, this is an important feature. Will add it in v0.11 (probably in September)

**Comment by lmrisdal** [comment]
Awesome to hear! I would also like to request/suggest to be able to create subflows inside other subflows, i.e. recursive subflows.

**Comment by artem-mangilev** [comment]
> Awesome to hear! I would also like to request/suggest to be able to create subflows inside other subflows, i.e. recursive subflows.

Yeah I'll check the react flow implemented this, seems like a complex feature

**Comment by artem-mangilev** [comment]
@lmrisdal @elnipa  I implemented subflows here, the API is similar to `reactflow`: https://github.com/artem-mangilev/ngx-vflow/releases/tag/v0.11.0

Recursive subflows works. But I realized that we also need some resizing functionality (for regular nodes too), decided to add it in the next release

**Comment by elnipa** [comment]
> @lmrisdal @elnipa I implemented subflows here, the API is similar to `reactflow`: https://github.com/artem-mangilev/ngx-vflow/releases/tag/v0.11.0
> 
> Recursive subflows works. But I realized that we also need some resizing functionality (for regular nodes too), decided to add it in the next release

wow, congrats. Impressive speed. I just tested that feature and indeed the resizing functionality would make sense (manually and optionally auto-resize when pushing children out of bounds).

And a collapsing function would be amazing to hide all (sub-)children.

I saw in your code that you are still on Angular 16. Are you planning to update to v17/18 and using the new control flow structure and signal inputs? There are some (auto) migrations in place in meanwhile.

**Comment by lmrisdal** [comment]
Awesome job! I'll start looking into implementation today!

**Comment by artem-mangilev** [comment]
> wow, congrats. Impressive dev speed. 

Thanks!

> And a collapsing function would be amazing to hide all (sub-)children

Yea, I will push it to the backlog

> I saw in your code that you are still on Angular 16. Are you planning to update to v17/18 and using the new control flow structure and signal inputs? There are some (auto) migrations in place in meanwhile.

The library is compatible with v17 and v18, and from a user's perspective, there shouldn't be any difference between the internal versions. However, I plan to upgrade to v17 in the first major release to use signal inputs and the new control flow. This will help squezze performance and potentially reduce the bundle size by removing the dependency on `CommonModule`. Additionally, I want to expose an API as standalone components/directives while maintaining backward compatibility with the current single-module solution.

**Comment by artem-mangilev** [comment]
I'll try hard to publish a major release with Angular 17 during this year

**Comment by artem-mangilev** [comment]
> Auto-resizing of the parent container based on the children would have been very nice! But doesn't look like even react flow has that, so might be a tougher problem?
yea, what complexities I see:
- Resizing should work recursively: when a parent is resized, we should check if it has its own parent and resize that parent as well
- We should provide convenient event containing all resized nodes, allowing clients to easily sync changes with the backend

> Also wondering if this would work together with layout engines such as the vizdom example?
Do you mean the current implementation of subflows? I guess it depends on the layout engine, according to [this](https://github.com/xyflow/xyflow/discussions/3495) issue, ElkJS supports subflows, so probably I should add an example with ElkJS.
Vizdom doesn't seem to support subflows

**Comment by lmrisdal** [comment]
Yeah, I figured Vizdom didn't support it. Currently looking into Dagre and ElkJS to see if they can work for me! Dagre should work with subflows according to React Flow docs, but I did notice that in the issue you linked someone said it didn't - so maybe I'll try out ElkJS first.
