### ISSUE TITLE
[Feature request] Edge buttons

### ISSUE THREAD

**Issue by lmrisdal** [artem-mangilev/ngx-vflow#86]
Hi again! I find myself in need of putting buttons between nodes as I'm working on this workflow builder. React Flow seems to have this functionality: https://reactflow.dev/examples/edges/custom-edges

Again using Azure Logic Apps as an example for what I mean:
![image](https://github.com/user-attachments/assets/2c0774b7-64b8-49e9-b732-5a84c61c64fb)

**Comment by artem-mangilev** [comment]
Hi! There is a labels feature: https://www.ngx-vflow.org/features/labels
You can pass there a custom content, a button for example

**Comment by lmrisdal** [comment]
Oh thanks, this is perfect! I was looking on the custom edges doc page and couldn't find anything 😅
