### ISSUE TITLE
Size is not reflected correctly when used with “@angular/material”.

### ISSUE THREAD

**Issue by takevox** [artem-mangilev/ngx-vflow#87]
When used with “@angular/material”, even if <vflow view=“auto”> is written, the width and height of the internal svg element is set to “0” and is not displayed correctly.

When clicked, the width and height change to “100%” and are displayed correctly, but is there any way to avoid the width and height of the svg element being set to “0” in the initial view?

**Comment by artem-mangilev** [comment]
Hi! Could you please provide a stackblitz example for me to easily identify how to fix this?

**Comment by takevox** [comment]
How about this?

https://github.com/takevox/materialtest

**Comment by artem-mangilev** [comment]
It's fine, I'll run in locally, thanks.

**Comment by artem-mangilev** [comment]
@takevox fixed in `0.13.0-0`

**Comment by takevox** [comment]
Thank you.

I will try the `0.13.0` branch.

**Comment by takevox** [comment]
I tried it with https://github.com/artem-mangilev/ngx-vflow/commit/b12a70eb73b4ccb74fd2f88122d3b35846010867  and it worked!

Thanks!

**Comment by artem-mangilev** [comment]
Great! I'll publish a `0.13.0` with this fix today or tomorrow

**Comment by takevox** [comment]
I have updated to `0.13.0` on my project and can confirm that the problem has been resolved!
Thanks for a great product!

**Comment by artem-mangilev** [comment]
> Thanks for a great product!
Thank you! So I'm closing the issue
