### ISSUE TITLE
Custom handles context improvements

### ISSUE THREAD

**Issue by muccijacopo** [artem-mangilev/ngx-vflow#91]
This is the current interface of HandleTemplateImplicitContext
```
interface HandleTemplateImplicitContext {
  point: Signal<{ x: number, y: number }>
  state: Signal<'valid' | 'invalid' | 'idle'>
}
```
It would be very helpful to add more data to the context, like node's data. Right now I think it's not possible to implement dynamic behaviour on the custom handle template based on its node. 

For my use-case this is enough but maybe you could also add the possibility to pass a custom context to handles.
` <handle position="left" type="target" [id]="ctx.node.data.input1" [template]="squareHandleTemplate" [templateContext]="{ visible: true }" />`

**Comment by artem-mangilev** [comment]
I'll add the node to context in the next version (`0.14`)

**Comment by artem-mangilev** [comment]
Hi! Added `ctx.node` for `<handle />` template here:
https://github.com/artem-mangilev/ngx-vflow/releases/tag/v0.14.1

**Comment by muccijacopo** [comment]
Awesome! @artem-mangilev Thanks so much.
